apiVersion: v1
kind: Service
metadata:
  name: fast-api
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: fast-api
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: http
