name: Build and push the latest build to staging

on:
  push:
    branches: [ main ]

jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2



      - name: Build and push staging images
        uses: docker/build-push-action@v2
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          repository: fast-api
          tags: latest
          
  deploy:
    runs-on: ubuntu-20.04
    needs: build_push_image # Will wait for the execution of the previous job

    steps:
       - uses: actions/checkout@v2

       - name: Helm tool installer
         uses: Azure/setup-helm@v3
         with: 
           version: v3.3.1

       - name: Get AKS Credentials
         uses: Azure/aks-set-context@v1
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
           resource-group: python-api-rg
           cluster-name: aks-python-api
       - name: Run Heml Deploy
         run: |
            echo "ACR_NAME: ${{ secrets.ACR_NAME }}"
            echo "ACR_REG: ${{ secrets.ACR_REG }}"
            echo "IMAGE: ${{ secrets.IMAGE }}"
            echo "DB_URL: ${{ secrets.DB_URL }}"
            echo "DNS_NAME: ${{ secrets.DNS_NAME }}"
            helm upgrade \
              --install \
              --create-namespace \
              --atomic \
              --wait \
              --namespace staging \
              fast-api \
              ./kubernetes/fast-api \
              --set image.repository=${{ secrets.ACR_NAME }} \
              --set dns.name=${{ secrets.DNS_NAME }} \
              --set db.URL=${{ secrets.DB_URL}}

         
