name: Build and push the latest build to staging

on:
  push:
    branches: [ main ]

jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push staging images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.ACR_NAME}}/fast-api:latest
          
  deploy:
    runs-on: ubuntu-20.04
    needs: build_push_image
    steps:
       - uses: actions/checkout@v2

       - name: Helm tool installer
         uses: Azure/setup-helm@v3
         with: 
           version: v3.3.1

       - name: Get AKS Credentials
         uses: Azure/aks-set-context@v1
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
           resource-group: python-api-rg
           cluster-name: aks-python-api
       - name: Run Heml Deploy
         run: |
            helm upgrade \
              --install \
              --create-namespace \
              --atomic \
              --wait \
              --namespace staging \
              fast-api \
              ./kubernetes/fast-api \
              --set image.repository=${{ secrets.ACR_NAME }} \
              --set dns.name=${{ secrets.DNS_NAME }} \
              --set db.URL=${{ secrets.DB_URL}} \
              --set secret.key=${{ secrets.SECRET_KEY }}

         
